dist: trusty
# only build develop, master & production branch
branches:
  only:
    - master
    - develop
    - production
addons:
  sonarcloud:
    organization: 'thinhtran3588'
    token:
      secure: 'RQBiAQdwIm/T3o8OzH9Yl0BAAwU0wUfEXgCoLPaIerjIWEFyuPNqtpaWX7CnGJ7F0S4SjSRsydJvzHPLVKIQeHycyzr3E+vHRgq+7MrPnidHLdlewXRqd/iFwqIAxVNdiVBsDcDozr0JWBBycmH7xzXo0YbbKyg41frM/YLJEzB92lHees78V+RwT146S31E0DHJf0vXiAJhN8YetNAzwegH1B5mg3M3brnKJpsitkQLlQf6sCnyg0fieK/vcPr1SN7E2Yz6/mfOnQ0pQC0B8e9MeZmxmCb5+szP8bNv40r7VhyX4O3g4lQXnjEh4g95VFKNEHq5rdFLLfMULf2p14oAHmE+FTXU3+NwhIq5JGmrxYfi34HINVUZlvCbZ1I6o+IHTYBWOQtdhWqriEVNdIFR7opV+tvL2ax0CYAT+zxErIBUY5iRqoMEmVQFaWAUBHL5LFtOcaBLlgKOy3R2V7Wk+PPZm6Lu8qC0jG3aHdMcEJHsL++l9Js51cZuV/sz/XVML+CS7PptWfJSor4X8wTWZf6ZVbBL4MGvXa4bhD8evJecSwBfDEEh1X4PJ1Cpfxy72ub+5rjrrVSDuFNeOTRdunXN4ps5cP8uwJISII1PZhU791JWtPf2UiHC9rBLK8Cltxbt9F9CgCYPVbGlTUm4wTEwN9e6fAPifSG1YV4='
language: node_js
node_js: 10.16.0
before_install:
  - nvm install 10.16.0
  # apply production configuration
  - openssl aes-256-cbc -K $encrypted_ee75ad30a7ba_key -iv $encrypted_ee75ad30a7ba_iv -in production.zip.enc -out production.zip -d
  - unzip -o production.zip
  - npm install -g yarn
  - yarn
jobs:
  include:
    - stage: Validate
      script: yarn validate &&
        yarn coveralls &&
        sonar-scanner
    - stage: Publish production
      if: branch = production
      script: pip install --user awscli &&
        npm install -g serverless &&
        curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash &&
        yarn job production &&
        yarn serverless-prepare &&
        yarn serverless-update-s3 &&
        yarn serverless-deploy
