# only build develop, master & production branch
branches:
  only:
    - master
    - develop
    - production
    - travis-test
language: node_js
node_js: 10.16.0
before_install:
  - nvm install 10.16.0
  # apply production configuration
  - openssl aes-256-cbc -K $encrypted_ee75ad30a7ba_key -iv $encrypted_ee75ad30a7ba_iv -in production.zip.enc -out production.zip -d
  - unzip -o production.zip
  - npm install -g yarn
  - yarn
jobs:
  include:
    - stage: Validate
      if: branch != travis-test
      script: yarn job production &&
        yarn build &&
        yarn validate &&
        yarn coveralls
    - stage: Publish
      if: branch = travis-test
      script: pip install --user awscli &&
        yarn job production &&
        yarn serverless-prepare &&
        yarn serverless-update-s3 &&
        npm install -g serverless &&
        yarn serverless-deploy
