version: "3"

services:
  web:
    environment:
      - NODE_ENV=production
    build: .
    command: yarn start
    volumes:
      - storage:/node_app/storage
    ports:
      - "3000:3000"
volumes:
  storage:
