org: thinhtran3588
app: web-starter-kit
service: web-starter-kit-main
provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  memorySize: 256 # optional, in MB, default is 1024
  timeout: 60 # optional, in seconds, default is 6
  environment:
    NODE_ENV: production
functions:
  web:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: dist/lamda.handler
    description: web starter kit
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
